In [87]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e7/sample_submission.csv
/kaggle/input/playground-series-s5e7/train.csv
/kaggle/input/playground-series-s5e7/test.csv

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
train = pd.read_csv('/kaggle/input/playground-series-s5e7/train.csv')
test = pd.read_csv('/kaggle/input/playground-series-s5e7/test.csv')
sample_submision = pd.read_csv('/kaggle/input/playground-series-s5e7/sample_submission.csv')

In [90]:
sample_submision

         id Personality
0     18524   Extrovert
1     18525   Extrovert
2     18526   Extrovert
3     18527   Extrovert
4     18528   Extrovert
...     ...         ...
6170  24694   Extrovert
6171  24695   Extrovert
6172  24696   Extrovert
6173  24697   Extrovert
6174  24698   Extrovert

[6175 rows x 2 columns]

In [91]:
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         18524 non-null  int64
 1   Time_spent_Alone           17334 non-null  float64
 2   Stage_fear                 16631 non-null  object
 3   Social_event_attendance    17344 non-null  float64
 4   Going_outside              17058 non-null  float64
 5   Drained_after_socializing  17375 non-null  object
 6   Friends_circle_size        17470 non-null  float64
 7   Post_frequency             17260 non-null  float64
 8   Personality                18524 non-null  object
dtypes: float64(5), int64(1), object(3)
memory usage: 1.3+ MB

,id,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency
count,18524.000000,17334.000000,17344.000000,17058.000000,17470.000000,17260.000000
mean,9261.500000,3.137764,5.265106,4.044319,7.996737,4.982097
std,5347.562529,3.003786,2.753359,2.062580,4.223484,2.879139
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4630.750000,1.000000,3.000000,3.000000,5.000000,3.000000
50%,9261.500000,2.000000,5.000000,4.000000,8.000000,5.000000
75%,13892.250000,4.000000,8.000000,6.000000,12.000000,7.000000
max,18523.000000,11.000000,10.000000,7.000000,15.000000,10.000000

In [92]:
train.isnull().sum()

id                              0
Time_spent_Alone             1190
Stage_fear                   1893
Social_event_attendance      1180
Going_outside                1466
Drained_after_socializing    1149
Friends_circle_size          1054
Post_frequency               1264
Personality                     0
dtype: int64

In [93]:
train.sample(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
11508,11508,NaN,No,6.0,4.0,No,13.0,9.0,Extrovert
18360,18360,2.0,No,5.0,3.0,No,8.0,6.0,Extrovert
13681,13681,3.0,No,6.0,5.0,No,13.0,5.0,Extrovert
10703,10703,NaN,Yes,2.0,NaN,Yes,3.0,0.0,Introvert
18501,18501,10.0,Yes,2.0,2.0,Yes,1.0,NaN,Introvert
8758,8758,0.0,No,8.0,5.0,No,7.0,3.0,Extrovert
2973,2973,1.0,No,9.0,3.0,No,10.0,3.0,Extrovert
6948,6948,0.0,NaN,4.0,7.0,No,14.0,8.0,Extrovert
2189,2189,3.0,No,4.0,5.0,No,15.0,8.0,Extrovert
18445,18445,1.0,No,7.0,3.0,No,7.0,5.0,Extrovert

In [94]:
print(train['Time_spent_Alone'].value_counts())
print(train['Stage_fear'].value_counts())
print(train['Social_event_attendance'].value_counts())
print(train['Going_outside'].value_counts())
print(train['Drained_after_socializing'].value_counts())
print(train['Friends_circle_size'].value_counts())
print(train['Post_frequency'].value_counts())
print(train['Personality'].value_counts())

Time_spent_Alone
0.0     3139
3.0     3081
2.0     3039
1.0     2973
4.0     1079
5.0      633
10.0     587
8.0      582
7.0      581
6.0      574
9.0      574
11.0     492
Name: count, dtype: int64
Stage_fear
No     12609
Yes     4022
Name: count, dtype: int64
Social_event_attendance
4.0     2073
9.0     2063
7.0     2031
5.0     1985
6.0     1984
8.0     1945
3.0     1703
2.0     1063
0.0     1055
1.0      978
10.0     464
Name: count, dtype: int64
Going_outside
5.0    2923
3.0    2822
4.0    2703
6.0    2702
7.0    2170
0.0    1324
2.0    1279
1.0    1135
Name: count, dtype: int64
Drained_after_socializing
No     13313
Yes     4062
Name: count, dtype: int64
Friends_circle_size
5.0     1669
4.0     1317
12.0    1317
8.0     1281
10.0    1267
11.0    1253
14.0    1188
6.0     1146
7.0     1124
9.0     1061
13.0    1048
15.0     943
3.0      866
2.0      770
1.0      753
0.0      467
Name: count, dtype: int64
Post_frequency
3.0     2258
7.0     1827
5.0     1788
6.0     1767
9.0     1744
8.0     1734
4.0     1688
2.0     1291
0.0     1272
1.0     1214
10.0     677
Name: count, dtype: int64
Personality
Extrovert    13699
Introvert     4825
Name: count, dtype: int64

In [95]:
print(train['Time_spent_Alone'].unique())
print(train['Stage_fear'].unique())
print(train['Social_event_attendance'].unique())
print(train['Going_outside'].unique())
print(train['Drained_after_socializing'].unique())
print(train['Friends_circle_size'].unique())
print(train['Post_frequency'].unique())
print(train['Personality'].unique())

[ 0.  1.  6.  3.  2.  4. nan  5.  9. 10.  7.  8. 11.]
['No' 'Yes' nan]
[ 6.  7.  1.  4.  8.  2.  5. nan  0.  9.  3. 10.]
[ 4.  3.  0.  5. nan  1.  6.  2.  7.]
['No' nan 'Yes']
[15. 10.  3. 11. 13. nan  4.  0. 14.  5.  9. 12.  8.  2.  1.  6.  7.]
[ 5.  8.  0. nan  3.  4.  2.  9. 10.  6.  7.  1.]
['Extrovert' 'Introvert']

In [96]:
fill1 = ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside', 'Friends_circle_size', 'Post_frequency']
train[fill1] = train[fill1].fillna(-1)
ohencode = ['Stage_fear', 'Drained_after_socializing', 'Personality']
train = pd.get_dummies(train, columns=ohencode, drop_first=True)

In [97]:
fill1 = ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside', 'Friends_circle_size', 'Post_frequency']
test[fill1] = test[fill1].fillna(-1)
ohencode = ['Stage_fear', 'Drained_after_socializing']
test = pd.get_dummies(test, columns=ohencode, drop_first=True)

In [98]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18524 entries, 0 to 18523
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             18524 non-null  int64
 1   Time_spent_Alone               18524 non-null  float64
 2   Social_event_attendance        18524 non-null  float64
 3   Going_outside                  18524 non-null  float64
 4   Friends_circle_size            18524 non-null  float64
 5   Post_frequency                 18524 non-null  float64
 6   Stage_fear_Yes                 18524 non-null  bool
 7   Drained_after_socializing_Yes  18524 non-null  bool
 8   Personality_Introvert          18524 non-null  bool
dtypes: bool(3), float64(5), int64(1)
memory usage: 922.7 KB

In [99]:
y = train['Personality_Introvert']
X = train.drop('Personality_Introvert', axis=1)

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [101]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Accuracy', accuracy_score(y_pred, y_test))

Accuracy 0.9686909581646423

In [102]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Accuracy', accuracy_score(y_pred, y_test))

Accuracy 0.9686909581646423

In [103]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators' : [50, 150, 300],
    'max_depth' : [3, 5, 7],
    'learning_rate' : [0.01, 0.1, 0.2]
}

model = GradientBoostingClassifier()

gridsearch = GridSearchCV(
    estimator = model,
    param_grid = param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

gridsearch.fit(X_train, y_train)

bestModel = gridsearch.best_estimator_
ypred = bestModel.predict(test)
y_pred = np.where(ypred == 0, 'Extrovert', 'Introvert')

In [104]:
submission = pd.DataFrame({
    'id': test['id'],
    'Prediction': y_pred
})

submission.to_csv('submission.csv', index=False)
df = pd.read_csv('submission.csv')
df.head()

      id Prediction
0  18524  Extrovert
1  18525  Introvert
2  18526  Extrovert
3  18527  Extrovert
4  18528  Introvert

In [105]:
df['Prediction'].value_counts()

Prediction
Extrovert    4616
Introvert    1559
Name: count, dtype: int64